server {
    listen 80;
    server_name api.yourdomain.com; # Replace with your backend domain

    # Use Docker's internal DNS resolver
    resolver 127.0.0.11 valid=30s;

    location / {
        set $admin_backend "http://admin-web:80";
        proxy_pass $admin_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name patient.yourdomain.com; # Replace with your patient app domain

    resolver 127.0.0.11 valid=30s;

    location / {
        set $patient_frontend "http://patient-deploymeta:3000";
        proxy_pass $patient_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name doctor.yourdomain.com; # Replace with your doctor app domain

    resolver 127.0.0.11 valid=30s;

    location / {
        set $doctor_frontend "http://doctor-deploymeta:3000";
        proxy_pass $doctor_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


